language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t majeedmo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true majeedmo/docker-react npm run test